const connectToMongo = require("./db")
const express = require('express')
const cors = require('cors')
const fetchuser = require('./middleware/fetchuser')
require('dotenv').config()

const app = express()
app.use(cors())
app.use(express.json())
app.use('/auth/user',require("./routes/user"))
// Public routes - no authentication required (front office)
app.use('/room', require("./routes/roomPublic"))
app.use('/accommodation', require("./routes/accommodationPublic"))
app.use('/event', require("./routes/roomEventPublic"))
// Protected routes - require authentication and check if user still exists (back office)
app.use('/room', fetchuser, require("./routes/room"))
app.use('/accommodation', fetchuser, require("./routes/accommodation"))
app.use('/invoice', fetchuser, require("./routes/invoice"))
app.use('/event', fetchuser, require("./routes/roomEvent"))
app.get('/',(req,res)=>{
    res.send("hello!")
})
app.listen(process.env.PORT, () => {
    console.log(`Server running on port ${process.env.PORT}`)
})